batch_type: numel
batch_bins: 1500000
accum_grad: 8
max_epoch: 25
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", 
]

input_size: 2048

encoder_conf:
    output_size: 512
    normalize_before: false
    freeze_finetune_updates: 100000000
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
    # w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec2_vox_960h_new.pt
    # w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt
    w2v_dir_path: ./downloads/wav2vec_pretrained_models

decoder: stateless
decoder_conf:
    embed_size: 512
    embed_dropout_rate: 0.2

joint_network_conf:
    joint_space_size: 512

model_conf:
    transducer_weight: 1.0
    auxiliary_ctc_weight: 0.0
    fastemit_lambda: 0.0
    report_cer: True
    report_wer: True
    # length_normalized_loss: false

# optimizer
optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

unused_parameters: true

frontend: null

normalize: null

specaug: null