# This configuration requires 4 GPUs with 32GB memory
batch_type: numel
batch_bins: 26000000
accum_grad: 4
max_epoch: 60
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
val_scheduler_criterion:
    - valid
    - loss
keep_nbest_models: 10

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 17
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: false
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
  n_fft: 512
  hop_length: 160

optim: adamw
optim_conf:
    lr: 2.0
    betas: [0.9, 0.98]
    weight_decay: 0.0001
scheduler: noamlr
scheduler_conf:
    warmup_steps: 10000
    model_size: 512
    

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
