# This configuration requires 4 GPUs with 32GB memory
batch_type: numel
batch_bins: 26000000
accum_grad: 4
max_epoch: 60
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
val_scheduler_criterion:
    - valid
    - loss
keep_nbest_models: 10

model_conf:
    report_cer: True
    report_wer: True

encoder_conf:
    main_conf:
      pos_wise_act_type: swish
      conv_mod_act_type: swish
      pos_enc_dropout_rate: 0.2
      dynamic_chunk_training: False
      short_chunk_size: 25
      left_chunk_size: 4
    input_conf:
      vgg_like: True
    body_conf:
    - block_type: conformer
      linear_size: 2048
      hidden_size: 512
      heads: 8
      dropout_rate: 0.1
      pos_wise_dropout_rate: 0.1
      att_dropout_rate: 0.1
      conv_mod_kernel_size: 31
      num_blocks: 17


frontend_conf:
  n_fft: 512
  hop_length: 160


optim: adamw
optim_conf:
    lr: 2.0
    betas: [0.9, 0.98]
    weight_decay: 0.0001
scheduler: noamlr
scheduler_conf:
    warmup_steps: 10000
    model_size: 512

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
