# general
batch_type: numel
batch_bins: 12000000
accum_grad: 4
max_epoch: 25 # 100 produces better results.
patience: none
init: none
num_att_plot: 0

freeze_param: [
    "encoder",
    # "decoder",
    # "joint_network",
    # "ctc",
]
init_param: [
    # "exp/4lstm/valid.loss.ave_10best.pth:encoder:encoder",
    # "exp/4lstm/valid.loss.ave_10best.pth:joint_network:joint_network",
    # "exp/ctc_prediction_network/encoder.pth:ctc:ctc",
    "exp/asr_ctc_conformer_new_ctc_new/60epoch.pth:encoder:encoder",
    "exp/asr_ctc_conformer_new_ctc_new/60epoch.pth:ctc_lo:ctc_lin",
    "exp/4lstm/valid.loss.ave_10best.pth:decoder:decoder",
]
ignore_init_mismatch: true

model_conf:
    report_cer: True
    report_wer: True

encoder_conf:
    main_conf:
      pos_wise_act_type: swish
      conv_mod_act_type: swish
      pos_enc_dropout_rate: 0.2
      dynamic_chunk_training: False
      short_chunk_size: 25
      left_chunk_size: 4
    input_conf:
      vgg_like: True
    body_conf:
    - block_type: conformer
      linear_size: 2048
      hidden_size: 512
      heads: 8
      dropout_rate: 0.1
      pos_wise_dropout_rate: 0.1
      att_dropout_rate: 0.1
      conv_mod_kernel_size: 31
      num_blocks: 17

decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 4
    embed_size: 512
    hidden_size: 640
    dropout_rate: 0.1
    embed_dropout_rate: 0.2

joint_network_conf:
    joint_space_size: 640

frontend_conf:
  n_fft: 512
  hop_length: 160

# optimizer
optim: adam
optim_conf:
    lr: 0.0015
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

# criterion
val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10 # 20 produces slightly better results.

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
